version: '3'
services:
    app:
        build: ./docker/php/
        container_name: app-curriculumn
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - server

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: nginx-curriculumn
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - server

    dbmysql:
        build: ./docker/mysql
        container_name: mysql-curriculumn
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: 'app'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/.dbdata:/var/lib/mysql
        networks:
            - server
    node:
        image: node:22
        container_name: node
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - server
        command: bash -c "npm install && tail -f /dev/null"

networks:
    server:
        driver: bridge




